import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'dt-bg': '#0B0E14',
                'outline': '#908fa0',
                'on-secondary-container': '#e6ecff',
                'primary-fixed-dim': '#c0c1ff',
                'on-primary-fixed': '#07006c',
                'surface-container-highest': '#31353e',
                'on-secondary': '#002e6a',
                'secondary-container': '#0566d9',
                'on-tertiary-fixed-variant': '#6900b3',
                'surface-dim': '#0f131b',
                'primary-fixed': '#e1e0ff',
                'surface-container-high': '#262a32',
                'dt-error': '#ffb4ab',
                'surface-variant': '#31353e',
                'surface': '#0f131b',
                'on-error-container': '#ffdad6',
                'dt-primary': '#c0c1ff',
                'tertiary-fixed-dim': '#ddb7ff',
                'dt-secondary': '#adc6ff',
                'primary-container': '#8083ff',
                'on-error': '#690005',
                'outline-variant': '#464554',
                'surface-tint': '#c0c1ff',
                'secondary-fixed': '#d8e2ff',
                'secondary-fixed-dim': '#adc6ff',
                'on-primary-container': '#0d0096',
                'inverse-surface': '#dfe2ee',
                'dt-tertiary': '#ddb7ff',
                'on-tertiary-container': '#400071',
                'on-surface-variant': '#c7c4d7',
                'surface-container': '#1c2028',
                'on-tertiary-fixed': '#2c0051',
                'on-surface': '#dfe2ee',
                'tertiary-container': '#b76dff',
                'inverse-primary': '#494bd6',
                'on-secondary-fixed': '#001a42',
                'on-primary': '#1000a9',
                'on-background': '#dfe2ee',
                'on-tertiary': '#490080',
                'background': '#0f131b',
                'surface-bright': '#353942',
                'on-secondary-fixed-variant': '#004395',
                'error-container': '#93000a',
                'surface-container-lowest': '#0a0e16',
                'inverse-on-surface': '#2c3039',
                'tertiary-fixed': '#f0dbff',
                'surface-container-low': '#181c24',
                'on-primary-fixed-variant': '#2f2ebe',
            },
            fontFamily: {
                sans: ['Geist', ...defaultTheme.fontFamily.sans],
                mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
            },
            fontSize: {
                'display': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
                'h1': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
                'h2': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
                'h3': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
                'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
                'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
                'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
                'code': ['13px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
        },
    },

    plugins: [forms],
};
